export const RESET_STATE_ACTION = '/Containers/PageTwo/RESET_STATE_ACTION';
export const GET_CURRENT_METHOD_ACTION = '/Containers/PageTwo/GET_CURRENT_METHOD_ACTION';
export const SET_CURRENT_METHOD_ACTION = '/Containers/PageTwo/SET_CURRENT_METHOD_ACTION';